// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"nick_name" form:"nick_name" uri:"nick_name"
	Nickname string `protobuf:"bytes,1,opt,name=Nickname,proto3" json:"nick_name" form:"nick_name" uri:"nick_name"`
	// @inject_tag: json:"user_name" form:"user_name" uri:"user_name"
	Username string `protobuf:"bytes,2,opt,name=Username,proto3" json:"user_name" form:"user_name" uri:"user_name"`
	// @inject_tag: json:"password" form:"password" uri:"password"
	Password string `protobuf:"bytes,3,opt,name=Password,proto3" json:"password" form:"password" uri:"password"`
	// @inject_tag: json:"password_confirm" form:"password_confirm" uri:"password_confirm"
	PasswordConfirm string `protobuf:"bytes,4,opt,name=PasswordConfirm,proto3" json:"password_confirm" form:"password_confirm" uri:"password_confirm"`
	// @inject_tag: json:"user_id" form:"user_id" uri:"user_id"
	UserID        uint64 `protobuf:"varint,5,opt,name=UserID,proto3" json:"user_id" form:"user_id" uri:"user_id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserRequest) GetPasswordConfirm() string {
	if x != nil {
		return x.PasswordConfirm
	}
	return ""
}

func (x *UserRequest) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type UserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"user_id" form:"user_id" uri:"user_id"
	UserID uint64 `protobuf:"varint,1,opt,name=UserID,proto3" json:"user_id" form:"user_id" uri:"user_id"`
	// @inject_tag: json:"nick_name" form:"nick_name" uri:"nick_name"
	Nickname string `protobuf:"bytes,2,opt,name=Nickname,proto3" json:"nick_name" form:"nick_name" uri:"nick_name"`
	// @inject_tag: json:"user_name" form:"user_name" uri:"user_name"
	Username      string `protobuf:"bytes,3,opt,name=Username,proto3" json:"user_name" form:"user_name" uri:"user_name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserResponse) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UserResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserDetailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"user_response" form:"user_response" uri:"user_response"
	UserDetail *UserResponse `protobuf:"bytes,1,opt,name=UserDetail,proto3" json:"user_response" form:"user_response" uri:"user_response"`
	// @inject_tag: json:"code" form:"code"" uri:"code""
	Code int64 `protobuf:"varint,2,opt,name=Code,proto3" json:"code" form:"code" uri:"code"`
	// @inject_tag: json:"msg" form:"msg"" uri:"msg""
	Msg           string `protobuf:"bytes,3,opt,name=Msg,proto3" json:"msg" form:"msg" uri:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDetailResponse) Reset() {
	*x = UserDetailResponse{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDetailResponse) ProtoMessage() {}

func (x *UserDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDetailResponse.ProtoReflect.Descriptor instead.
func (*UserDetailResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserDetailResponse) GetUserDetail() *UserResponse {
	if x != nil {
		return x.UserDetail
	}
	return nil
}

func (x *UserDetailResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserDetailResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UserCommonResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @inject_tag: json:"code" form:"code"" uri:"code""
	Code int64 `protobuf:"varint,1,opt,name=Code,proto3" json:"code" form:"code" uri:"code"`
	// @inject_tag: json:"msg" form:"msg"" uri:"msg""
	Msg string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"msg" form:"msg" uri:"msg"`
	// @inject_tag: json:"data" form:"data"" uri:"data""
	Data          string `protobuf:"bytes,3,opt,name=Data,proto3" json:"data" form:"data" uri:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCommonResponse) Reset() {
	*x = UserCommonResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCommonResponse) ProtoMessage() {}

func (x *UserCommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCommonResponse.ProtoReflect.Descriptor instead.
func (*UserCommonResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserCommonResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UserCommonResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UserCommonResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\"\xa3\x01\n" +
	"\vUserRequest\x12\x1a\n" +
	"\bNickname\x18\x01 \x01(\tR\bNickname\x12\x1a\n" +
	"\bUsername\x18\x02 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPassword\x12(\n" +
	"\x0fPasswordConfirm\x18\x04 \x01(\tR\x0fPasswordConfirm\x12\x16\n" +
	"\x06UserID\x18\x05 \x01(\x04R\x06UserID\"^\n" +
	"\fUserResponse\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\x04R\x06UserID\x12\x1a\n" +
	"\bNickname\x18\x02 \x01(\tR\bNickname\x12\x1a\n" +
	"\bUsername\x18\x03 \x01(\tR\bUsername\"i\n" +
	"\x12UserDetailResponse\x12-\n" +
	"\n" +
	"UserDetail\x18\x01 \x01(\v2\r.UserResponseR\n" +
	"UserDetail\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\x03R\x04Code\x12\x10\n" +
	"\x03Msg\x18\x03 \x01(\tR\x03Msg\"N\n" +
	"\x12UserCommonResponse\x12\x12\n" +
	"\x04Code\x18\x01 \x01(\x03R\x04Code\x12\x10\n" +
	"\x03Msg\x18\x02 \x01(\tR\x03Msg\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\tR\x04Data2\x8b\x02\n" +
	"\vUserService\x12.\n" +
	"\tUserLogin\x12\f.UserRequest\x1a\x13.UserDetailResponse\x121\n" +
	"\fUserRegister\x12\f.UserRequest\x1a\x13.UserCommonResponse\x12/\n" +
	"\n" +
	"UserLogout\x12\f.UserRequest\x1a\x13.UserCommonResponse\x127\n" +
	"\x12UserChangePassword\x12\f.UserRequest\x1a\x13.UserCommonResponse\x12/\n" +
	"\n" +
	"UserDelete\x12\f.UserRequest\x1a\x13.UserCommonResponseB\aZ\x05user/b\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_proto_goTypes = []any{
	(*UserRequest)(nil),        // 0: UserRequest
	(*UserResponse)(nil),       // 1: UserResponse
	(*UserDetailResponse)(nil), // 2: UserDetailResponse
	(*UserCommonResponse)(nil), // 3: UserCommonResponse
}
var file_user_proto_depIdxs = []int32{
	1, // 0: UserDetailResponse.UserDetail:type_name -> UserResponse
	0, // 1: UserService.UserLogin:input_type -> UserRequest
	0, // 2: UserService.UserRegister:input_type -> UserRequest
	0, // 3: UserService.UserLogout:input_type -> UserRequest
	0, // 4: UserService.UserChangePassword:input_type -> UserRequest
	0, // 5: UserService.UserDelete:input_type -> UserRequest
	2, // 6: UserService.UserLogin:output_type -> UserDetailResponse
	3, // 7: UserService.UserRegister:output_type -> UserCommonResponse
	3, // 8: UserService.UserLogout:output_type -> UserCommonResponse
	3, // 9: UserService.UserChangePassword:output_type -> UserCommonResponse
	3, // 10: UserService.UserDelete:output_type -> UserCommonResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
